import { BLACK, BLUE, GREEN, RED, RgbFloat, WHITE, YELLOW } from '../color/ColorFloat';
import { Effect } from './Effect';
import {
  ChangeColorEffect,
  FlipColorEffect,
  MeteorEffect,
  PingPongEffect,
  RainbowGradientEffect1D,
  SingleColorRainEffect,
  RotatingColorGradientEffect,
  SineEffect,
  SingleColorEffect,
  SingleHslColorEffect,
  StaticAlternatingColorEffect,
  StaticColorGradientEffect,
  TestPerLedEffect,
  TwinkleEffect,
  TwoAlternatingColorFadingEffect,
  TwoAlternatingCustomColorFadingEffect,
  MultiColorRainEffect,
  StaticCustomColorGradientEffect,
  TestAllLedsFlash,
} from './Effects1D';
import {
  CloudsEffect,
  GravityFountain,
  PlasmaEffect,
  PulseScanner,
  RainbowGradientEffect2D,
  Slime,
} from './Effects2D';

const redGreenBlue: RgbFloat[] = [RED, GREEN, BLUE];

export const effects: Record<string, Effect<any>> = {
  flip_color: new FlipColorEffect(redGreenBlue),
  change_color: new ChangeColorEffect(redGreenBlue),
  red: new SingleColorEffect(RED),
  green: new SingleColorEffect(GREEN),
  blue: new SingleColorEffect(BLUE),
  black: new SingleColorEffect(BLACK),
  white: new SingleColorEffect(WHITE),
  choose_hsl: new SingleHslColorEffect(),
  alternate_rgb: new StaticAlternatingColorEffect([RED, GREEN, BLUE]),
  alternate_rgby: new StaticAlternatingColorEffect([RED, GREEN, BLUE, YELLOW]),
  gradient_red_yellow: new StaticColorGradientEffect([RED, YELLOW]),
  gradient_rgb: new StaticColorGradientEffect([RED, GREEN, BLUE]),
  gradient_rgbr: new StaticColorGradientEffect([RED, GREEN, BLUE, RED]),
  rotating_gradient_rgbr: new RotatingColorGradientEffect([RED, GREEN, BLUE, RED]),
  gradient_black_red: new StaticColorGradientEffect([BLACK, RED]),
  gradient_black_green: new StaticColorGradientEffect([BLACK, GREEN]),
  gradient_black_blue: new StaticColorGradientEffect([BLACK, BLUE]),
  gradient_black_white: new StaticColorGradientEffect([BLACK, WHITE]),
  gradient_custom: new StaticCustomColorGradientEffect(),
  two_alternating_colors: new TwoAlternatingColorFadingEffect(RED, BLUE),
  two_alternating_colors_custom: new TwoAlternatingCustomColorFadingEffect(),
  rainbow: new RainbowGradientEffect1D(),
  meteor: new MeteorEffect(),
  rain_single_color: new SingleColorRainEffect(),
  rain_multi_color: new MultiColorRainEffect(),
  twinkle: new TwinkleEffect(),
  sine: new SineEffect(),
  ping_pong: new PingPongEffect(),
  rainbow_2d: new RainbowGradientEffect2D(),
  pulse_scanner: new PulseScanner(),
  slime: new Slime(),
  clouds: new CloudsEffect(),
  plasma: new PlasmaEffect(),
  gravity_fountain: new GravityFountain(),
  test_per_led: new TestPerLedEffect(),
  test_all_leds_flash: new TestAllLedsFlash(),
};
